[profile.release]
panic = "unwind"

[workspace]
members = [
    # "pallets/*",
    # "pallets/substrate-channel",
    "pallets/types",
    # "pallets/leaf-provider/runtime-api",
    # "pallets/leaf-provider/rpc",
    # "pallets/beefy-light-client/runtime-api",
    # "pallets/beefy-light-client/rpc",
]

resolver = "2"
