[profile.release]
panic = "unwind"

[workspace]
members = [
	"pallets/sora2-trustless-bridge/beefy-light-client",
	"pallets/sora2-trustless-bridge/beefy-light-client/rpc",
	"pallets/sora2-trustless-bridge/common",
]
