[workspace]
members = [
    "pallets/trustless-eth-bridge/dispatch",
    "pallets/trustless-eth-bridge/types",
    "pallets/trustless-eth-bridge/substrate-app",
    "pallets/trustless-eth-bridge/substrate-channel",
]

resolver = "2"

[profile.release]
panic = 'unwind'
