[package]
name = "jetton-app"
description = "Jetton App"
version = "0.1.1"
authors = ['Polka Biome Ltd. <jihoon@tutanota.de>']
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.130", optional = true }
codec = { version = "3", package = "parity-scale-codec", default-features = false, features = [
    "derive",
] }
scale-info = { version = "2", default-features = false, features = ["derive"] }
hex = { package = "rustc-hex", version = "2.1.0", default-features = false }
hex-literal = { version = "0.4.1", default-features = false }

frame-benchmarking = { workspace = true, default-features = false, optional = true }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }

traits = { workspace = true, default-features = false, optional = true }
currencies = { workspace = true, default-features = false, optional = true }
dispatch = { path = "../dispatch", default-features = false, optional = true }

bridge-types = { path = "../types", default-features = false }

[dev-dependencies]
dispatch = { path = "../dispatch" }
sp-keyring = { workspace = true }
sp-keystore = { workspace = true }
pallet-balances = { workspace = true }
tokens = { workspace = true }
traits = { workspace = true }
currencies = { workspace = true }
hex-literal = { version = "0.4.1" }
bridge-types = { path = "../types", features = ["test"] }

[features]
default = ["std"]
std = [
    "serde/std",
    "hex/std",
    "codec/std",
    "scale-info/std",
    "frame-support/std",
    "frame-system/std",
    "sp-core/std",
    "sp-std/std",
    "sp-io/std",
    "sp-runtime/std",
    "bridge-types/std",
    "frame-benchmarking/std",
    "traits/std",
    "currencies/std",
    "dispatch/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "traits",
    "currencies",
    "dispatch",
    "dispatch/runtime-benchmarks",
]

try-runtime = ["frame-support/try-runtime"]
